apply plugin: 'com.android.application'

//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.

// Custom definitions may go here

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packaging {
        jniLibs.useLegacyPackaging true
        resources {
            excludes += '/META-INF/DEPENDENCIES'
            excludes += '/META-INF/LICENSE'
            excludes += '/META-INF/LICENSE.txt'
            excludes += '/META-INF/license.txt'
            excludes += '/META-INF/NOTICE'
            excludes += '/META-INF/NOTICE.txt'
            excludes += '/META-INF/notice.txt'
            excludes += '/META-INF/ASL2.0'
            excludes += '/META-INF/*.kotlin_module'
            excludes += '/META-INF/io.netty.versions.properties'
            excludes += '/META-INF/INDEX.LIST'
        }
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
}

dependencies {
    implementation project(':FtcRobotController')

    implementation "com.acmerobotics.dashboard:dashboard:0.5.1" // FTC Dashboard


    // Marrow (for Zones)
    implementation 'com.skeletonarmyftc.marrow:core:1.1.2'


    //noinspection NewerVersionAvailable
    implementation("org.ejml:ejml-simple:0.39") {
        exclude group: "org.ejml", module: "ejml-all"
    }

    // JUnit 5
    //noinspection NewerVersionAvailable
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.11.3"
    //noinspection NewerVersionAvailable
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.11.3"
}
